import { ConnectWallet, useAddress, useLogin } from "@thirdweb-dev/react";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const address = useAddress();
  const login = useLogin();
  const [addressFromServer, setAddressFromServer] = useState("");

  const getAddressFromServer = async () => {
    const response = await fetch("/api/getaddress");

    if (!response.ok) return alert("Not authenticated");

    const data = await response.json();

    setAddressFromServer(data.walletAddress);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1>elo</h1>
      <ConnectWallet />

      <button onClick={getAddressFromServer}>Get address from server</button>
      <div>{addressFromServer}</div>
    </div>
  );
}